<?php
	require("common.php");
	session_start();

	verifyUserData();
	$fieldsString = createCurlData($DATABASE, $MERCHANTID, $MERCHANTUSER, $MERCHANTPIN);
	$curlData = curlRequest($MERCHANTURL, $fieldsString);
	if ($curlData["result"] === "0") {
		displayConfirmation($curlData, $DATABASE);
		registerCourses($DATABASE);
	} else if ($curlData["Code"]) { 
		error($curlData["Name"], $curlData["Message"] . " This error was autogenerated. Contact EXCO if you need assistance");
	}


	//verifies user data, throws errors if they arent signed in, if there is no data,
	//if there are no classes, or if there's missing credit data
	function verifyUserData() {
		if (empty($_SESSION["id"])) {
			error("No Logon Info", "Please login to continue");
		} if (count($_SESSION["cart"]) < 2) {
			error("No classes", "You don't have any classes to sign up for!");
		} if (empty($_POST["card"]) || empty($_POST["exp"]) ||
				empty($_POST["cvc"]) || empty($_POST["phone"])) {
			error("Missing Information", "You did not complete a required field");
		}
	}


	//Create all the data for the Curl request. returns a bare string.
	function createCurlData($DATABASE, $MERCHANTID, $MERCHANTUSER, $MERCHANTPIN) {
		//grab the user data from teh database for freshest bariables
		$db = new DB();
		$user = $db -> select("SELECT email, first_name, last_name, phone, type 
		                       FROM " . $DATABASE . ".users 
		                       WHERE id = " . $db -> quote($_SESSION["id"]));

		//decide just how much we're charging the user right now.
		$charge = 5;
		if ($user[0]["type"] == "general") {
			$charge = 12;
		}
		$charge = $charge * (count($_SESSION["cart"]) / 2);

		//create the invoice name
		$invoice = "Class";
		if (count($_SESSION["cart"]) > 2) {
			$invoice . "es";
		}
		for ($i = 0; $i < count($_SESSION["cart"]); $i+= 2) {
			$invoice = $invoice . " " . $_SESSION["cart"][$i] . ":" . $_SESSION["cart"][$i + 1];
		} 
		if (strlen($invoice) > 25) { //maximum length set by virtual merchant
			$invoice = "EXCO Classes";
		}

		//standardize the data we're about to stringify
		$fields = array(
			"ssl_test_mode"=>"TRUE", //set to false to not send to credit companies, but return approved
			"ssl_card_number"=>urlencode($_POST["card"]),
			"ssl_exp_date"=>urlencode($_POST["exp"]),
			"ssl_cvv2cvc2"=>urlencode($_POST["cvc"]),
			"ssl_merchant_id"=> $MERCHANTID,
			"ssl_user_id"=> $MERCHANTUSER,
			"ssl_pin"=> $MERCHANTPIN,
			"ssl_account_data" => "",
			"ssl_transaction_type"=>"ccsale",
			"ssl_show_form"=>"false",
			"ssl_cvv2cvc2_indicator"=>"1",
			"ssl_amount"=>urlencode($charge),
			"ssl_salestax"=>"0",
			"ssl_invoice_number"=>urlencode($invoice),
			"ssl_first_name"=>urlencode($user[0]["first_name"]),
			"ssl_last_name"=>urlencode($user[0]["last_name"]),
			"ssl_email"=>urlencode($user[0]["email"]),
			'ssl_avs_address'=>'NONE',
			'ssl_avs_zip'=>'NONE',
			"ssl_result_format"=>"ASCII"
		);

		$fieldsString = "";
		foreach ($fields as $key => $value) {
			$fieldsString .= $key . "=" . $value . "&";
		}

		return $fieldsString;
	}


	//requests the data from the merchant. returns the parsed data.
	function curlRequest($MERCHANTURL, $fieldsString) {
		//Create the request and populate the data
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, $MERCHANTURL);
		curl_setopt($ch, CURLOPT_POST, 1);
		//set post data string
		curl_setopt($ch, CURLOPT_POSTFIELDS, $fieldsString);
		//these two options are frequently necessary to avoid SSL errors with PHP
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

		//execute the curl
		$curlResult = curl_exec($ch);

		//close the curl session
		curl_close($ch);
		
		$curlArray = preg_split("/(ssl_)|(error)/", $curlResult);
		$values = array();
		foreach ($curlArray as $part) {
			$equal = strpos($part, "=");
			$key = trim(substr($part, 0, $equal));
			$value = trim(substr($part, $equal + 1));
			$values[$key] = $value;
		}

		return $values;
	}


	//gives the user a recpeit that their request was successful
	function displayConfirmation($c, $DATABASE) {
		head(); ?>

		<section class="confirmation">
			<div class="container">
				<h1>Order Successful!</h1>
				<p>Thank you for taking classes with the Experimental College!
					You should receive an email shortly detailing the classes you applied for.
					Your order information is below.</p>
				<table>
					<tr>
						<td>Card Ending in: </td>
						<td><?= substr($c["card_number"], 12) ?></td>
					</tr>
					<tr>
						<td>Amount: </td>
						<td>$<?= $c["amount"] ?></td>
					</tr>
					<tr>
						<td>Invoice: </td>
						<td><?= $c["invoice_number"] ?></td>
					</tr>
					<tr>
						<td>Classes: </td>
						<td></td>
					</tr>
				
					<?php for ($i = 0; $i < count($_SESSION["cart"]); $i+= 2) { 
						$db = new DB();
						$course = $db -> select("SELECT name FROM " . $DATABASE . ".courses 
						                         WHERE id = " . $db->quote($_SESSION["cart"][$i])); ?>
						<tr>
							<td></td>
							<td><?= $course[0]["name"] ?></td>
						</tr>

					<?php } ?>

				</table>
				<p>Head over to <a href="mycourses.php">my courses</a> at any time to view your
					currently enrolled classes</p>
			</div>
		</section>

		<?php tail();
	}


	//Add all the classes from the user's session into the database. This clears the user's 
	// cart session!
	function registerCourses($DATABASE) {
		$db = new DB();
		for ($i = 0; $i < count($_SESSION["cart"]); $i+=2) {
			$id = $db->quote($_SESSION["cart"][$i]);
			$section = $db->quote($_SESSION["cart"][$i + 1]); 
			$db -> query("INSERT INTO " . $DATABASE . ".registrations
			             (course_id, course_section, user_id) VALUES
			             (" . $id . ", " . $section . ", " . $db->quote($_SESSION["id"]) . ")");
		}
		$_SESSION["cart"] = null;
	}


?>